version: "3"
services:
  intermine_builder:
    container_name: ${MINE}_builder
    networks:
      - frontend
      - backend
    build:
      context: ./intermine_builder
      dockerfile: ./intermine_builder.Dockerfile
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - ./data/workdir:/home/intermine/workdir
      - ./data/maven.m2:/home/intermine/.m2
      - ./data/properties.intermine:/home/intermine/.intermine

  postgres:
    container_name: ${MINE}_postgres
    networks:
      - backend
    build:
      context: ./postgres
      dockerfile: ./postgres.Dockerfile
    restart: unless-stopped
    user: 29023:1010
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - MINE_NAME=${MINE}

  solr:
    container_name: ${MINE}_solr
    networks:
      - backend
    build:
      context: ./solr
      dockerfile: ./solr.Dockerfile
    restart: unless-stopped
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ./data/solr:/var/solr
    environment:
      - MEM_OPTS="-Xmx8g -Xms1g"
      - MINE_NAME=${MINE}

  tomcat:
    container_name: ${MINE}_tomcat
    networks:
      - frontend
      - backend
    build:
      context: ./tomcat
      dockerfile: ./tomcat.Dockerfile
    restart: unless-stopped
    volumes:
      - tomcat-webapps:/usr/local/tomcat/webapps:Z

  bluegenes:
    container_name: ${MINE}_bluegenes
    networks:
      - frontend
      - backend
    image: intermine/bluegenes:latest
    restart: unless-stopped
    volumes:
      - ./data/tools:/tools
    environment:
      - BLUEGENES_DEFAULT_SERVICE_ROOT="https://${MINE}.org/${MINE}"
      - BLUEGENES_BACKEND_SERVICE_ROOT="http://tomcat:8080/${MINE}"
      - BLUEGENES_DEFAULT_MINE_NAME=${MINE}
      - BLUEGENES_DEFAULT_NAMESPACE=${MINE}

  nginx:
    container_name: ${MINE}_nginx
    networks:
      - frontend
    build:
      context: ./nginx
      dockerfile: ./nginx.Dockerfile
    restart: unless-stopped
    ports:
      - ${HTTP_PORT}:80

volumes:
  tomcat-webapps:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
